package ar.uba.fi.celdas7568.ciudad.gui;

public enum ItemCiudad {
	
	SUBTE, TEATRO, BOMBEROS, TRANSITO, COLECTIVO, EXCLUSIVA, CARA, COMISARIA, UNIVERSIDAD, BAR, RESTORAN, PELIGRO, HOSPITAL, IGLESIA, PARQUE, SUCIO, AGENTE;

}
